'use strict';

// Banque de questions QCM.
// Convention : la PREMIÈRE option est toujours la bonne réponse.
// Le serveur mélange les options à chaque partie.

const Q = (q, options, code) => ({ q, options, code: code || null });

const THEMES = {
  javascript: {
    name: `JavaScript`, icon: `🟨`, kind: `Langage`,
    questions: [
      Q(`Que renvoie typeof null ?`, [`"object"`, `"null"`, `"undefined"`, `"number"`]),
      Q(`Quel mot-clé déclare une variable de bloc qu'on ne peut pas réassigner ?`, [`const`, `let`, `var`, `static`]),
      Q(`Qu'affiche ce code ?`, [`false`, `true`, `undefined`, `NaN`], `console.log(0.1 + 0.2 === 0.3);`),
      Q(`Que renvoie cette expression ?`, [`[2, 4, 6]`, `[1, 2, 3]`, `12`, `undefined`], `[1, 2, 3].map(x => x * 2)`),
      Q(`Que vaut '5' + 3 ?`, [`"53"`, `8`, `"8"`, `NaN`]),
      Q(`Que vaut '5' - 3 ?`, [`2`, `"53"`, `"2"`, `NaN`]),
      Q(`Quelle méthode ajoute un élément à la fin d'un tableau ?`, [`push()`, `pop()`, `shift()`, `unshift()`]),
      Q(`Que vérifie l'opérateur === ?`, [`La valeur ET le type, sans conversion`, `La valeur seulement, après conversion de type`, `Uniquement le type`, `Que les deux variables existent`]),
      Q(`Que fait JSON.parse() ?`, [`Transforme une chaîne JSON en valeur JavaScript`, `Transforme un objet en chaîne JSON`, `Vérifie qu'un fichier JSON est valide`, `Télécharge un fichier JSON`]),
      Q(`Que renvoie toujours une fonction déclarée avec async ?`, [`Une Promise`, `Un callback`, `undefined`, `Un générateur`]),
      Q(`Que renvoie typeof NaN ?`, [`"number"`, `"NaN"`, `"undefined"`, `"object"`]),
      Q(`Lequel n'est PAS un type primitif en JavaScript ?`, [`Array`, `Symbol`, `BigInt`, `undefined`]),
      Q(`Qu'affiche ce code ?`, [`4`, `3`, `undefined`, `TypeError`], `const a = [1, 2, 3];\nconst b = a;\nb.push(4);\nconsole.log(a.length);`),
      Q(`Dans quel ordre s'affichent les lettres ?`, [`A D C B`, `A B C D`, `A D B C`, `A C D B`], `console.log('A');\nsetTimeout(() => console.log('B'), 0);\nPromise.resolve().then(() => console.log('C'));\nconsole.log('D');`),
      Q(`Que vaut [...'abc'] ?`, [`['a', 'b', 'c']`, `'abc'`, `['abc']`, `SyntaxError`]),
      Q(`Quelle méthode crée un nouveau tableau avec seulement les éléments qui passent un test ?`, [`filter()`, `map()`, `reduce()`, `forEach()`]),
      Q(`Que vaut Boolean('') ?`, [`false`, `true`, `undefined`, `''`]),
      Q(`Dans une fonction fléchée, à quoi correspond this ?`, [`Au this du contexte englobant (lexical)`, `À l'objet qui appelle la fonction`, `Toujours à window`, `À la fonction elle-même`]),
      Q(`Que se passe-t-il ?`, [`Ça fonctionne : obj.a vaut 2`, `TypeError : obj est une constante`, `SyntaxError`, `obj.a reste à 1`], `const obj = { a: 1 };\nobj.a = 2;`),
      Q(`Qu'affiche ce code ?`, [`5`, `undefined`, `null`, `ReferenceError`], `const { x = 5 } = {};\nconsole.log(x);`),
      Q(`Que vaut null ?? 'défaut' ?`, [`'défaut'`, `null`, `undefined`, `false`]),
      Q(`Que vaut 0 || 'x' ?`, [`'x'`, `0`, `true`, `false`]),
      Q(`Quelle méthode réduit un tableau à une seule valeur (ex : une somme) ?`, [`reduce()`, `map()`, `filter()`, `some()`]),
      Q(`Que renvoie typeof undefined ?`, [`"undefined"`, `"object"`, `"null"`, `"none"`]),
      Q(`Que vaut [1, 2, 3].length ?`, [`3`, `2`, `4`, `undefined`]),
      Q(`Quelle méthode transforme une chaîne JSON en objet ?`, [`JSON.parse()`, `JSON.stringify()`, `JSON.decode()`, `JSON.toObject()`]),
      Q(`Qu'affiche ce code ?`, [`[1, 2, 3, 4]`, `[[1, 2], [3, 4]]`, `[1, 2]`, `TypeError`], `console.log([1, 2].concat([3, 4]));`),
      Q(`Que fait Array.isArray([]) ?`, [`Renvoie true`, `Renvoie false`, `Lève une erreur`, `Renvoie "array"`]),
      Q(`Quelle boucle parcourt les VALEURS d'un tableau ?`, [`for...of`, `for...in`, `for each`, `while of`]),
      Q(`Que vaut 10 % 3 ?`, [`1`, `3`, `0`, `3.33`]),
      Q(`Comment déclare-t-on une fonction fléchée qui renvoie x+1 ?`, [`x => x + 1`, `function => x + 1`, `=> (x) x + 1`, `x -> x + 1`]),
      Q(`Que fait la méthode .trim() sur une chaîne ?`, [`Retire les espaces en début et fin`, `Coupe la chaîne en deux`, `Met en majuscules`, `Inverse la chaîne`]),
      Q(`Qu'affiche ce code ?`, [`2`, `1`, `3`, `undefined`], `const s = new Set([1, 1, 2]);\nconsole.log(s.size);`),
      Q(`Que vaut Number("12px") ?`, [`NaN`, `12`, `"12"`, `0`]),
      Q(`Quelle méthode attend toutes les promesses d'un tableau ?`, [`Promise.all()`, `Promise.wait()`, `Promise.every()`, `await.all()`]),
    ],
  },

  python: {
    name: `Python`, icon: `🐍`, kind: `Langage`,
    questions: [
      Q(`Qu'affiche ce code ?`, [`<class 'list'>`, `<class 'array'>`, `<class 'tuple'>`, `list`], `print(type([]))`),
      Q(`Que renvoie len("Python") ?`, [`6`, `5`, `7`, `Une erreur`]),
      Q(`Quel mot-clé définit une fonction nommée ?`, [`def`, `function`, `fn`, `func`]),
      Q(`Qu'affiche print(10 // 3) ?`, [`3`, `3.3333333333333335`, `3.0`, `4`]),
      Q(`Qu'affiche print(2 ** 3) ?`, [`8`, `6`, `9`, `23`]),
      Q(`Lequel de ces types est immuable ?`, [`tuple`, `list`, `dict`, `set`]),
      Q(`Que produit cette compréhension de liste ?`, [`[0, 1, 4, 9]`, `[1, 4, 9, 16]`, `[0, 1, 2, 3]`, `[0, 2, 4, 6]`], `[x * x for x in range(4)]`),
      Q(`Que vaut "abc"[::-1] ?`, [`'cba'`, `'abc'`, `'c'`, `IndexError`]),
      Q(`Qu'affiche print(bool([])) ?`, [`False`, `True`, `None`, `Une erreur`]),
      Q(`Quel bloc sert à intercepter une exception ?`, [`try / except`, `try / catch`, `do / rescue`, `catch / finally`]),
      Q(`Qu'affiche ce code ?`, [`4`, `5`, `3`, `TypeError`], `x = [1, 2, 3]\nx.append([4, 5])\nprint(len(x))`),
      Q(`Qu'affiche ce code ?`, [`0`, `None`, `KeyError`, `'b'`], `d = {'a': 1}\nprint(d.get('b', 0))`),
      Q(`À quoi sert la méthode __init__ d'une classe ?`, [`Initialiser l'instance à sa création`, `Supprimer l'instance`, `Importer le module`, `Déclarer une méthode statique`]),
      Q(`Qu'affiche print(3 == 3.0) ?`, [`True`, `False`, `TypeError`, `None`]),
      Q(`Quelle commande crée un environnement virtuel ?`, [`python -m venv env`, `pip install venv env`, `python --virtual env`, `pip env create`]),
      Q(`Qu'affiche print("ab" * 3) ?`, [`ababab`, `ab3`, `TypeError`, `['ab', 'ab', 'ab']`]),
      Q(`Que renvoie set([1, 2, 2, 3]) ?`, [`{1, 2, 3}`, `[1, 2, 3]`, `{1, 2, 2, 3}`, `(1, 2, 3)`]),
      Q(`Quel mot-clé transforme une fonction en générateur ?`, [`yield`, `return`, `async`, `generate`]),
      Q(`Qu'est-ce que la PEP 8 ?`, [`Le guide de style officiel du code Python`, `Le gestionnaire de paquets`, `Une version de Python`, `Un framework web`]),
      Q(`Qu'affiche ce code ?`, [`[(1, 3), (2, 4)]`, `[1, 2, 3, 4]`, `[(1, 2), (3, 4)]`, `[[1, 3], [2, 4]]`], `print(list(zip([1, 2], [3, 4])))`),
      Q(`Qu'affiche print(type(5 / 2)) ?`, [`<class 'float'>`, `<class 'int'>`, `<class 'double'>`, `<class 'decimal'>`]),
      Q(`Qu'affiche ce code (piège classique) ?`, [`[1, 1]`, `[1]`, `[]`, `Une erreur`], `def f(l=[]):\n    l.append(1)\n    return l\n\nf()\nprint(f())`),
      Q(`Quel outil installe des paquets Python ?`, [`pip`, `npm`, `gem`, `cargo`]),
      Q(`Qu'affiche print("Hi".lower()) ?`, [`hi`, `HI`, `Hi`, `Une erreur`]),
      Q(`Que renvoie range(3) une fois converti en liste ?`, [`[0, 1, 2]`, `[1, 2, 3]`, `[0, 1, 2, 3]`, `[3]`]),
      Q(`Quel mot-clé crée une fonction anonyme ?`, [`lambda`, `def`, `func`, `anon`]),
      Q(`Qu'affiche print(5 % 2) ?`, [`1`, `2`, `2.5`, `0`]),
      Q(`Comment ajoute-t-on une paire clé/valeur à un dict d ?`, [`d['k'] = v`, `d.add('k', v)`, `d.push('k', v)`, `d += {'k': v}`]),
      Q(`Que fait la fonction enumerate() ?`, [`Elle renvoie des paires (index, valeur)`, `Elle compte les éléments`, `Elle trie la liste`, `Elle supprime les doublons`]),
      Q(`Qu'affiche print("a,b,c".split(",")) ?`, [`['a', 'b', 'c']`, `'a b c'`, `['a,b,c']`, `3`]),
      Q(`Quel mot-clé gère l'ouverture sûre d'un fichier (fermeture auto) ?`, [`with`, `try`, `open`, `using`]),
      Q(`Que vaut 3 * "ab" ?`, [`'ababab'`, `'ab3'`, `TypeError`, `6`]),
      Q(`Comment formate-t-on une f-string avec la variable nom ?`, [`f"Salut {nom}"`, `"Salut {nom}"`, `"Salut $nom"`, `f"Salut [nom]"`]),
      Q(`Que renvoie bool(0) ?`, [`False`, `True`, `0`, `None`]),
      Q(`Quelle méthode retire et renvoie le dernier élément d'une liste ?`, [`pop()`, `remove()`, `del()`, `shift()`]),
    ],
  },

  java: {
    name: `Java`, icon: `☕`, kind: `Langage`,
    questions: [
      Q(`Quelle est la signature classique du point d'entrée d'un programme Java ?`, [`public static void main(String[] args)`, `public void main()`, `static int main(String args)`, `void start(String[] args)`]),
      Q(`Combien de bits occupe un int en Java ?`, [`32`, `16`, `64`, `Ça dépend de la machine`]),
      Q(`Quel mot-clé permet à une classe d'hériter d'une autre ?`, [`extends`, `implements`, `inherits`, `super`]),
      Q(`Quel mot-clé permet à une classe d'implémenter une interface ?`, [`implements`, `extends`, `uses`, `interface`]),
      Q(`Comment compare-t-on le CONTENU de deux String ?`, [`s1.equals(s2)`, `s1 == s2`, `s1.compare(s2)`, `s1 === s2`]),
      Q(`Que signifie JVM ?`, [`Java Virtual Machine`, `Java Variable Method`, `Java Visual Manager`, `Joint Virtual Memory`]),
      Q(`Quelle interface de collection n'accepte pas les doublons ?`, [`Set`, `List`, `Queue`, `Deque`]),
      Q(`Que signifie final devant une variable ?`, [`Elle ne peut plus être réassignée`, `Elle devient globale`, `Elle est supprimée à la fin du bloc`, `Elle devient thread-safe`]),
      Q(`Qu'affiche ce code ?`, [`12`, `11`, `10`, `13`], `int x = 5;\nSystem.out.println(x++ + ++x);`),
      Q(`Quelle est la valeur par défaut d'un attribut de type int ?`, [`0`, `null`, `undefined`, `-1`]),
      Q(`Laquelle est une exception vérifiée (checked) ?`, [`IOException`, `NullPointerException`, `ArithmeticException`, `ArrayIndexOutOfBoundsException`]),
      Q(`Les objets String en Java sont…`, [`Immuables`, `Modifiables directement`, `Des types primitifs`, `Toujours stockés sur la pile`]),
      Q(`Quel modificateur rend un membre visible uniquement dans sa propre classe ?`, [`private`, `protected`, `public`, `package-private (aucun mot-clé)`]),
      Q(`Que fait le garbage collector ?`, [`Il libère la mémoire des objets qui ne sont plus référencés`, `Il supprime les fichiers .class inutiles`, `Il vide le cache du compilateur`, `Il supprime les variables final`]),
      Q(`Que produit le compilateur javac ?`, [`Des fichiers .class (bytecode)`, `Des fichiers .java`, `Des fichiers .exe`, `Des fichiers .obj`]),
      Q(`Comment obtient-on la taille d'un tableau arr ?`, [`arr.length`, `arr.length()`, `arr.size()`, `arr.count`]),
      Q(`Quelle est la relation entre int et Integer ?`, [`Integer est la classe enveloppe (wrapper) de int`, `Ce sont exactement les mêmes`, `int est un objet, Integer un primitif`, `Integer stocke des entiers sur 64 bits`]),
      Q(`Depuis Java 8, une interface peut contenir…`, [`Des méthodes default avec implémentation`, `Des constructeurs`, `Des attributs d'instance modifiables`, `Un main obligatoire`]),
      Q(`Que renvoie ce code ?`, [`2`, `4`, `6`, `[2, 4]`], `List.of(1, 2, 3, 4).stream()\n    .filter(n -> n % 2 == 0)\n    .count();`),
      Q(`Quelle est la complexité moyenne d'un get() dans une HashMap ?`, [`O(1)`, `O(n)`, `O(log n)`, `O(n²)`]),
      Q(`Que fait super() dans un constructeur ?`, [`Il appelle le constructeur de la classe parente`, `Il crée une super-classe`, `Il rend la méthode statique`, `Il appelle la méthode main`]),
      Q(`Quel mot-clé crée un objet ?`, [`new`, `create`, `alloc`, `make`]),
      Q(`Quelle classe sert à construire des chaînes modifiables efficacement ?`, [`StringBuilder`, `String`, `StringBuffer est le seul`, `CharArray`]),
      Q(`Que signifie static pour une méthode ?`, [`Elle appartient à la classe, pas à une instance`, `Elle ne peut pas être appelée`, `Elle est privée`, `Elle est thread-safe`]),
      Q(`Quel type représente un caractère unique ?`, [`char`, `String`, `character`, `byte`]),
      Q(`Comment afficher du texte dans la console ?`, [`System.out.println()`, `print()`, `console.log()`, `echo()`]),
      Q(`Quelle structure gère une paire clé/valeur ?`, [`HashMap`, `ArrayList`, `LinkedList`, `HashSet`]),
      Q(`Quel bloc s'exécute toujours, exception ou non ?`, [`finally`, `catch`, `else`, `always`]),
      Q(`Que signifie POO ?`, [`Programmation Orientée Objet`, `Programme Of Objects`, `Pointer Oriented Operations`, `Public Object Order`]),
      Q(`Quelle annotation indique qu'on redéfinit une méthode ?`, [`@Override`, `@Overload`, `@Redefine`, `@Super`]),
      Q(`Que vaut 7 / 2 en division entière (int) ?`, [`3`, `3.5`, `4`, `2`]),
    ],
  },

  csharp: {
    name: `C#`, icon: `🟪`, kind: `Langage`,
    questions: [
      Q(`Sur quelle plateforme s'exécute le code C# ?`, [`.NET (CLR)`, `La JVM`, `Node.js`, `Le Zend Engine`]),
      Q(`Comment déclarer une propriété auto-implémentée ?`, [`public int Age { get; set; }`, `public int Age => get set;`, `property int Age;`, `public get set int Age;`]),
      Q(`Que signifie var en C# ?`, [`Le type est déduit à la compilation (typage statique)`, `Le type est dynamique à l'exécution`, `La variable est globale`, `La variable est constante`]),
      Q(`Comment la classe B hérite-t-elle de A ?`, [`class B : A`, `class B extends A`, `class B inherits A`, `class B implements A`]),
      Q(`Que signifie LINQ ?`, [`Language Integrated Query`, `Linked Integer Query`, `Library In .NET Query`, `Logical Index Query`]),
      Q(`Que déclare int? x = null; ?`, [`Un entier nullable`, `Une erreur de compilation`, `Un entier qui vaut 0`, `Un pointeur`]),
      Q(`Que retourne généralement une méthode async qui ne renvoie pas de valeur ?`, [`Task`, `Thread`, `Promise`, `Future`]),
      Q(`À quoi sert le bloc using (var x = ...) { } ?`, [`Garantir l'appel de Dispose() à la fin du bloc`, `Installer un package NuGet`, `Déclarer une variable globale`, `Démarrer un nouveau thread`]),
      Q(`Lequel est un type valeur ?`, [`struct`, `class`, `string`, `object`]),
      Q(`Que fait l'opérateur ?? ?`, [`Il renvoie l'opérande de droite si celle de gauche est null`, `Il compare deux valeurs`, `C'est l'opérateur ternaire`, `Il lève une exception si la valeur est null`]),
      Q(`Qu'affiche ce code (avec using System.Linq) ?`, [`3`, `1`, `2`, `6`], `int[] nums = { 3, 1, 2 };\nConsole.WriteLine(nums.Max());`),
      Q(`Quel est le gestionnaire de paquets de .NET ?`, [`NuGet`, `npm`, `pip`, `Maven`]),
      Q(`Que signifie sealed sur une classe ?`, [`Elle ne peut pas être héritée`, `Elle ne peut pas être instanciée`, `Elle est thread-safe`, `Son code est chiffré`]),
      Q(`Une classe abstract…`, [`Ne peut pas être instanciée directement`, `Ne peut contenir aucune méthode`, `Est forcément statique`, `Ne peut pas être héritée`]),
      Q(`Quelle convention de nommage suit une interface en C# ?`, [`Préfixe I (ex : IRepository)`, `Suffixe _int`, `Préfixe Int`, `Tout en minuscules`]),
      Q(`Quel framework sert à créer des API et des sites web en C# ?`, [`ASP.NET Core`, `Django`, `Laravel`, `Spring Boot`]),
      Q(`Comment ajouter 5 à une List<int> nommée list ?`, [`list.Add(5);`, `list.push(5);`, `list.append(5);`, `list += 5;`]),
      Q(`Quelle syntaxe est une interpolation de chaîne en C# ?`, [`$"Bonjour {nom}"`, `f"Bonjour {nom}"`, `"Bonjour #{nom}"`, `"Bonjour %nom%"`]),
      Q(`foreach peut parcourir tout objet qui implémente…`, [`IEnumerable`, `IDisposable`, `IComparable`, `ICloneable`]),
      Q(`Les string en C# sont-elles immuables ?`, [`Oui, chaque modification crée une nouvelle chaîne`, `Non, on les modifie en place`, `Seulement en mode Release`, `Seulement si elles sont const`]),
      Q(`Quel mot-clé redéfinit une méthode virtual dans une classe dérivée ?`, [`override`, `overload`, `virtual`, `redefine`]),
      Q(`Comment affiche-t-on une ligne dans la console ?`, [`Console.WriteLine()`, `System.out.println()`, `print()`, `echo`]),
      Q(`Quel type représente un booléen ?`, [`bool`, `boolean`, `bit`, `logical`]),
      Q(`Quel mot-clé déclare une constante ?`, [`const`, `final`, `readonly only`, `static const`]),
      Q(`Comment nomme-t-on un bloc gérant une exception ?`, [`try / catch`, `try / except`, `begin / rescue`, `do / handle`]),
      Q(`Quelle collection générique est une liste dynamique ?`, [`List<T>`, `Array<T>`, `Vector<T>`, `Dict<T>`]),
      Q(`Que fait le mot-clé await ?`, [`Il attend la fin d'une tâche asynchrone`, `Il met le thread en pause 1s`, `Il lance un nouveau thread`, `Il annule une tâche`]),
      Q(`Comment déclarer un tableau d'entiers ?`, [`int[] t = new int[3];`, `int t[] = [3];`, `array<int> t;`, `int t = new[3];`]),
      Q(`Quelle est l'extension de fichier d'un projet C# ?`, [`.cs`, `.csharp`, `.net`, `.cpp`]),
      Q(`Que signifie le mot-clé null ?`, [`Absence de référence/valeur`, `Le nombre zéro`, `Une chaîne vide`, `false`]),
    ],
  },

  php: {
    name: `PHP`, icon: `🐘`, kind: `Langage`,
    questions: [
      Q(`Par quel symbole commence une variable PHP ?`, [`$`, `@`, `#`, `&`]),
      Q(`Quel opérateur concatène deux chaînes ?`, [`.`, `+`, `&`, `~`]),
      Q(`Qu'affiche ce code ?`, [`bool(true)`, `bool(false)`, `int(10)`, `NULL`], `<?php\n$a = "5";\n$b = 5;\nvar_dump($a == $b);`),
      Q(`Qu'affiche ce code ?`, [`bool(false)`, `bool(true)`, `int(5)`, `Une erreur`], `<?php\nvar_dump("5" === 5);`),
      Q(`Quelle fonction renvoie le nombre d'éléments d'un tableau ?`, [`count($tab)`, `length($tab)`, `$tab->length`, `size($tab)`]),
      Q(`Quelle superglobale contient les données d'un formulaire envoyé en POST ?`, [`$_POST`, `$POST`, `$_FORM`, `$_DATA`]),
      Q(`Qu'est-ce que Composer ?`, [`Le gestionnaire de dépendances de PHP`, `Un framework MVC`, `Un serveur web`, `Un moteur de templates`]),
      Q(`Quel est le moteur de templates de Laravel ?`, [`Blade`, `Twig`, `Smarty`, `Jinja`]),
      Q(`Contre quoi protègent principalement les requêtes préparées (PDO) ?`, [`Les injections SQL`, `Les attaques XSS`, `Les attaques DDoS`, `Le vol de session`]),
      Q(`Quelle fonction affiche le type ET la valeur d'une variable ?`, [`var_dump()`, `echo`, `print_type()`, `show()`]),
      Q(`Quelle fonction démarre (ou reprend) une session ?`, [`session_start()`, `start_session()`, `session_open()`, `$_SESSION->start()`]),
      Q(`Quelle fonction est recommandée pour hacher un mot de passe ?`, [`password_hash()`, `md5()`, `sha1()`, `base64_encode()`]),
      Q(`Que renvoie explode(",", "a,b,c") ?`, [`Un tableau ['a', 'b', 'c']`, `La chaîne "a b c"`, `Le nombre 3`, `La chaîne "abc"`]),
      Q(`Quelle est la différence entre include et require ?`, [`require provoque une erreur fatale si le fichier est absent`, `include est plus rapide`, `require ne fonctionne qu'une seule fois`, `Il n'y a aucune différence`]),
      Q(`Comment déclarer un tableau associatif ?`, [`['nom' => 'Ana']`, `['nom': 'Ana']`, `{nom: 'Ana'}`, `array('nom' = 'Ana')`]),
      Q(`Que signifie aujourd'hui l'acronyme PHP ?`, [`PHP: Hypertext Preprocessor`, `Personal Hosting Platform`, `Private Home Program`, `Python HTML Parser`]),
      Q(`Comment appeler la méthode demarrer() d'un objet $voiture ?`, [`$voiture->demarrer()`, `$voiture.demarrer()`, `$voiture=>demarrer()`, `voiture::demarrer()`]),
      Q(`Qu'affiche echo strlen("Hello"); ?`, [`5`, `4`, `6`, `Hello`]),
      Q(`Dans foreach ($t as $k => $v), que contient $k ?`, [`La clé`, `La valeur`, `Le dernier index`, `Le tableau entier`]),
      Q(`Que fait declare(strict_types=1); ?`, [`Active le typage strict des paramètres et retours scalaires`, `Interdit les variables globales`, `Active le mode debug`, `Rend toutes les variables constantes`]),
      Q(`Que vaut $x ?? 'défaut' si $x n'est pas définie ?`, [`'défaut'`, `null`, `Une erreur fatale`, `false`]),
      Q(`Comment afficher du texte en PHP ?`, [`echo "texte";`, `print_text("texte");`, `console.log("texte");`, `write("texte");`]),
      Q(`Quelle superglobale contient les données d'URL (query string) ?`, [`$_GET`, `$_POST`, `$_URL`, `$_QUERY`]),
      Q(`Quel symbole termine une instruction PHP ?`, [`;`, `.`, `:`, `,`]),
      Q(`Quelle fonction transforme un tableau en chaîne JSON ?`, [`json_encode()`, `json_decode()`, `to_json()`, `serialize_json()`]),
      Q(`Comment commenter une seule ligne ?`, [`// commentaire`, `# n'existe pas en PHP`, `<!-- commentaire -->`, `** commentaire`]),
      Q(`Quelle balise ouvre du code PHP ?`, [`<?php`, `<php>`, `<%`, `{{`]),
      Q(`Que renvoie array_map() ?`, [`Un nouveau tableau transformé`, `Le nombre d'éléments`, `Rien (void)`, `Le tableau trié`]),
      Q(`Quelle fonction vérifie qu'une clé existe dans un tableau ?`, [`array_key_exists()`, `in_array()`, `key_exists_value()`, `has_key()`]),
      Q(`Quel framework PHP utilise Symfony comme base ?`, [`Laravel`, `Django`, `Express`, `Rails`]),
    ],
  },

  sql: {
    name: `SQL`, icon: `🗄️`, kind: `Base de données`,
    questions: [
      Q(`Quelle commande lit des données dans une table ?`, [`SELECT`, `READ`, `GET`, `OPEN`]),
      Q(`Quelle clause filtre les lignes AVANT le regroupement ?`, [`WHERE`, `HAVING`, `ORDER BY`, `LIMIT`]),
      Q(`Quelle clause filtre les résultats APRÈS un GROUP BY ?`, [`HAVING`, `WHERE`, `FILTER BY`, `GROUP WHERE`]),
      Q(`Quelle clause trie les résultats ?`, [`ORDER BY`, `SORT BY`, `GROUP BY`, `ARRANGE BY`]),
      Q(`Quelle fonction compte le nombre de lignes ?`, [`COUNT(*)`, `SUM(*)`, `TOTAL(*)`, `NUMBER(*)`]),
      Q(`Que renvoie un INNER JOIN ?`, [`Uniquement les lignes qui ont une correspondance dans les deux tables`, `Toutes les lignes de la table de gauche`, `Toutes les lignes des deux tables`, `Le produit cartésien des deux tables`]),
      Q(`Que renvoie un LEFT JOIN ?`, [`Toutes les lignes de gauche, avec NULL quand il n'y a pas de correspondance`, `Seulement les lignes communes aux deux tables`, `Toutes les lignes de la table de droite`, `Uniquement les lignes de gauche sans correspondance`]),
      Q(`Quelle est la caractéristique d'une PRIMARY KEY ?`, [`Elle identifie chaque ligne de façon unique et ne peut pas être NULL`, `Elle peut contenir des doublons`, `Elle pointe forcément vers une autre table`, `Elle est facultative et peut être NULL`]),
      Q(`À quoi sert une FOREIGN KEY ?`, [`Référencer la clé d'une autre table pour garantir l'intégrité`, `Chiffrer une colonne`, `Accélérer les tris`, `Définir l'ordre des colonnes`]),
      Q(`Quelle commande supprime une table ET sa structure ?`, [`DROP TABLE`, `TRUNCATE TABLE`, `DELETE FROM`, `CLEAR TABLE`]),
      Q(`Comment tester si une colonne vaut NULL ?`, [`WHERE col IS NULL`, `WHERE col = NULL`, `WHERE col == NULL`, `WHERE col EQUALS NULL`]),
      Q(`Comment trouver les noms qui commencent par A ?`, [`WHERE nom LIKE 'A%'`, `WHERE nom = 'A*'`, `WHERE nom MATCH 'A'`, `WHERE nom CONTAINS 'A'`]),
      Q(`Quel mot-clé supprime les doublons dans un SELECT ?`, [`DISTINCT`, `UNIQUE`, `DIFFERENT`, `SINGLE`]),
      Q(`Quelle commande ajoute une ligne ?`, [`INSERT INTO`, `ADD INTO`, `PUT INTO`, `APPEND INTO`]),
      Q(`Quelle commande modifie des lignes existantes ?`, [`UPDATE ... SET`, `MODIFY ... SET`, `CHANGE ... TO`, `ALTER ... VALUES`]),
      Q(`Quelle commande modifie la structure d'une table (ex : ajouter une colonne) ?`, [`ALTER TABLE`, `UPDATE TABLE`, `MODIFY TABLE`, `CHANGE TABLE`]),
      Q(`Dans ACID, que signifie le A ?`, [`Atomicité`, `Accessibilité`, `Authentification`, `Agrégation`]),
      Q(`Que ne compte PAS COUNT(colonne) ?`, [`Les valeurs NULL`, `Les doublons`, `Les zéros`, `Les chaînes vides`]),
      Q(`Quelle est la différence entre UNION et UNION ALL ?`, [`UNION supprime les doublons, UNION ALL les conserve`, `UNION ALL supprime les doublons, UNION les conserve`, `UNION ALL trie le résultat`, `Aucune différence`]),
      Q(`Quel est l'effet principal d'un index ?`, [`Accélérer les recherches, au prix d'écritures un peu plus lentes`, `Chiffrer la table`, `Compresser les données`, `Sauvegarder automatiquement la table`]),
      Q(`Que renvoie LIMIT 5 OFFSET 10 ?`, [`5 lignes à partir de la 11e`, `10 lignes à partir de la 5e`, `Les lignes 5 à 10`, `15 lignes`]),
      Q(`Quelle fonction calcule une moyenne ?`, [`AVG()`, `MEAN()`, `MEDIAN()`, `AVERAGE()`]),
      Q(`Quel caractère joker remplace un seul caractère dans un LIKE ?`, [`_`, `%`, `*`, `?`]),
      Q(`Quelle commande supprime toutes les lignes mais garde la table ?`, [`TRUNCATE TABLE`, `DROP TABLE`, `REMOVE ALL`, `CLEAR TABLE`]),
      Q(`Quelle clause regroupe les lignes pour une agrégation ?`, [`GROUP BY`, `ORDER BY`, `CLUSTER BY`, `PARTITION`]),
      Q(`Que fait la fonction MAX() ?`, [`Renvoie la plus grande valeur`, `Compte les lignes`, `Additionne les valeurs`, `Renvoie la dernière ligne`]),
      Q(`Comment renommer une colonne dans le résultat ?`, [`SELECT col AS nom`, `SELECT col RENAME nom`, `SELECT nom = col`, `SELECT col -> nom`]),
      Q(`Que garantit une transaction avec COMMIT/ROLLBACK ?`, [`Valider ou annuler un ensemble d'opérations`, `Accélérer les requêtes`, `Chiffrer les données`, `Créer une sauvegarde`]),
      Q(`Quelle contrainte interdit les valeurs NULL dans une colonne ?`, [`NOT NULL`, `UNIQUE`, `CHECK`, `DEFAULT`]),
      Q(`Quel opérateur teste une liste de valeurs ?`, [`IN`, `AMONG`, `HAS`, `ANYOF`]),
    ],
  },

  htmlcss: {
    name: `HTML & CSS`, icon: `🎨`, kind: `Web`,
    questions: [
      Q(`Que signifie HTML ?`, [`HyperText Markup Language`, `HighText Machine Language`, `HyperTool Multi Language`, `Home Tool Markup Language`]),
      Q(`Quelle balise correspond au titre de plus haut niveau ?`, [`<h1>`, `<h6>`, `<head>`, `<header>`]),
      Q(`Quelle balise crée un lien hypertexte ?`, [`<a>`, `<link>`, `<href>`, `<url>`]),
      Q(`Quel attribut donne un texte alternatif à une image ?`, [`alt`, `title`, `src`, `desc`]),
      Q(`Quelle propriété CSS change la couleur du texte ?`, [`color`, `font-color`, `text-color`, `foreground`]),
      Q(`En flexbox, quelle propriété aligne les éléments sur l'axe principal ?`, [`justify-content`, `align-items`, `flex-align`, `text-align`]),
      Q(`Quel sélecteur cible l'élément dont l'id est "menu" ?`, [`#menu`, `.menu`, `menu`, `*menu`]),
      Q(`Ordre du modèle de boîte, de l'intérieur vers l'extérieur ?`, [`content → padding → border → margin`, `content → margin → border → padding`, `padding → content → border → margin`, `border → padding → content → margin`]),
      Q(`Avec box-sizing: border-box, la largeur (width) inclut…`, [`Le contenu, le padding et la bordure`, `Uniquement le contenu`, `Le contenu et la marge`, `La marge uniquement`]),
      Q(`Un élément en position: absolute se positionne par rapport à…`, [`Son plus proche ancêtre positionné (non static)`, `Toujours la fenêtre du navigateur`, `Son élément frère précédent`, `Toujours la balise <body>`]),
      Q(`Qu'est-ce qui a la plus forte spécificité (hors !important) ?`, [`Un style inline (attribut style)`, `Un sélecteur d'id`, `Un sélecteur de classe`, `Un sélecteur de balise`]),
      Q(`Quelle balise sémantique contient un bloc de navigation ?`, [`<nav>`, `<menu-bar>`, `<navigation>`, `<links>`]),
      Q(`Quelle syntaxe crée une media query pour les petits écrans ?`, [`@media (max-width: 600px) { ... }`, `@screen small { ... }`, `@responsive (600px) { ... }`, `#media (max-width: 600px) { ... }`]),
      Q(`Comment créer une grille de 3 colonnes égales ?`, [`grid-template-columns: repeat(3, 1fr);`, `grid-columns: 3;`, `grid: 3 equal;`, `columns-template: 3fr;`]),
      Q(`Quelle unité est relative à la taille de police de l'élément racine ?`, [`rem`, `em`, `px`, `vh`]),
      Q(`Quel champ de formulaire valide nativement une adresse e-mail ?`, [`<input type="email">`, `<email>`, `<input email>`, `<input type="mail">`]),
      Q(`Comment déclarer et utiliser une variable en CSS natif ?`, [`--couleur: red; puis var(--couleur)`, `$couleur: red; puis $couleur`, `@couleur: red; puis @couleur`, `var couleur = red; puis couleur`]),
      Q(`Quel est le doctype d'un document HTML5 ?`, [`<!DOCTYPE html>`, `<!DOCTYPE HTML5>`, `<html5>`, `<?xml html?>`]),
      Q(`À quoi sert z-index ?`, [`Gérer l'ordre d'empilement des éléments`, `Zoomer sur un élément`, `Régler la transparence`, `Définir l'ordre de tabulation`]),
      Q(`Quelle déclaration cache un élément tout en gardant sa place ?`, [`visibility: hidden;`, `display: none;`, `hidden: true;`, `remove: yes;`]),
      Q(`Quelle pseudo-classe s'applique au survol de la souris ?`, [`:hover`, `::hover`, `.hover`, `@hover`]),
      Q(`Quelle balise crée une liste à puces ?`, [`<ul>`, `<ol>`, `<li>`, `<list>`]),
      Q(`Quelle propriété CSS définit l'espace intérieur ?`, [`padding`, `margin`, `border`, `gap`]),
      Q(`Quelle unité est relative à la taille de police de l'élément racine ?`, [`rem`, `px`, `pt`, `vh`]),
      Q(`Quelle balise regroupe du contenu en ligne sans sémantique ?`, [`<span>`, `<div>`, `<section>`, `<p>`]),
      Q(`Quelle propriété CSS rend un conteneur flexible ?`, [`display: flex`, `display: block`, `float: left`, `position: flex`]),
      Q(`Quel attribut HTML rend un champ obligatoire ?`, [`required`, `mandatory`, `validate`, `needed`]),
      Q(`Quelle balise insère une image ?`, [`<img>`, `<image>`, `<picture> uniquement`, `<src>`]),
      Q(`Quelle règle CSS gère le responsive selon la largeur d'écran ?`, [`@media`, `@screen`, `@responsive`, `@viewport`]),
    ],
  },

  git: {
    name: `Git`, icon: `🌿`, kind: `Outil`,
    questions: [
      Q(`Quelle commande initialise un nouveau dépôt ?`, [`git init`, `git start`, `git new`, `git create`]),
      Q(`Comment ajouter tous les fichiers modifiés à l'index (staging) ?`, [`git add .`, `git index .`, `git commit .`, `git push .`]),
      Q(`Comment créer un commit avec un message ?`, [`git commit -m "message"`, `git save "message"`, `git push -m "message"`, `git commit "message"`]),
      Q(`Quelle commande crée une branche ET bascule dessus ?`, [`git checkout -b feature`, `git branch -m feature`, `git new feature`, `git merge -b feature`]),
      Q(`Quelle commande récupère les changements distants SANS les fusionner ?`, [`git fetch`, `git pull`, `git clone`, `git merge`]),
      Q(`git pull équivaut à…`, [`git fetch + git merge (ou rebase)`, `git push + git fetch`, `git clone + git add`, `git commit + git push`]),
      Q(`Quelle commande affiche l'historique des commits ?`, [`git log`, `git history`, `git status`, `git timeline`]),
      Q(`Comment annuler le dernier commit en GARDANT les modifications ?`, [`git reset --soft HEAD~1`, `git reset --hard HEAD~1`, `git delete HEAD`, `git undo --all`]),
      Q(`Que fait git revert <commit> ?`, [`Il crée un nouveau commit qui annule ce commit`, `Il efface ce commit de l'historique`, `Il restaure le dépôt distant`, `Il supprime la branche courante`]),
      Q(`Quelle commande met de côté temporairement des modifications non commitées ?`, [`git stash`, `git save`, `git hold`, `git shelf`]),
      Q(`À quoi sert le fichier .gitignore ?`, [`Lister les fichiers que Git ne doit pas suivre`, `Bloquer certains contributeurs`, `Ignorer les conflits de fusion`, `Configurer le dépôt distant`]),
      Q(`Que représente HEAD ?`, [`La référence vers le commit ou la branche actuellement extrait`, `Le tout premier commit`, `Le serveur distant`, `Toujours la branche main`]),
      Q(`Comment copier un dépôt distant en local ?`, [`git clone <url>`, `git copy <url>`, `git fork <url>`, `git download <url>`]),
      Q(`Quand survient un conflit de fusion ?`, [`Quand deux branches modifient les mêmes lignes différemment`, `Quand on crée trop de branches`, `Quand le dépôt est trop gros`, `À chaque git pull`]),
      Q(`Que fait git rebase main depuis une branche ?`, [`Il rejoue les commits de la branche par-dessus main`, `Il supprime la branche main`, `Il renomme la branche`, `Il crée un commit de fusion`]),
      Q(`Quelle commande montre les fichiers modifiés et ceux prêts à être commités ?`, [`git status`, `git log`, `git show`, `git check`]),
      Q(`Que fait git cherry-pick <commit> ?`, [`Il applique ce commit précis sur la branche courante`, `Il choisit le meilleur commit automatiquement`, `Il supprime ce commit`, `Il compare deux commits`]),
      Q(`Quel est le nom par défaut du dépôt distant après un clone ?`, [`origin`, `master`, `upstream`, `remote`]),
      Q(`Que montre git diff --staged ?`, [`Les différences entre l'index et le dernier commit`, `Les différences entre deux branches distantes`, `Les fichiers ignorés`, `L'historique des merges`]),
      Q(`Comment marquer la version v1.0 ?`, [`git tag v1.0`, `git label v1.0`, `git release v1.0`, `git mark v1.0`]),
      Q(`Une Pull Request, c'est…`, [`Une fonctionnalité des plateformes (GitHub, GitLab…) pour proposer et relire des changements`, `Une commande git pull-request`, `Un git pull forcé`, `Une branche protégée`]),
      Q(`Quelle commande initialise un dépôt Git ?`, [`git init`, `git start`, `git new`, `git create`]),
      Q(`Quelle commande enregistre les changements indexés ?`, [`git commit`, `git save`, `git push`, `git add`]),
      Q(`Quelle commande ajoute un fichier à l'index (staging) ?`, [`git add`, `git stage`, `git commit`, `git track`]),
      Q(`Quelle commande crée une nouvelle branche ?`, [`git branch nom`, `git new nom`, `git checkout --new nom`, `git create nom`]),
      Q(`Quelle commande récupère les changements distants et les fusionne ?`, [`git pull`, `git fetch only`, `git clone`, `git merge origin`]),
      Q(`Quelle commande affiche l'historique des commits ?`, [`git log`, `git history`, `git commits`, `git show-all`]),
      Q(`Que fait git clone ?`, [`Copie un dépôt distant en local`, `Duplique une branche`, `Fusionne deux dépôts`, `Supprime un dépôt`]),
      Q(`À quoi sert un fichier .gitignore ?`, [`Lister les fichiers que Git ne doit pas suivre`, `Supprimer des commits`, `Chiffrer le dépôt`, `Lister les contributeurs`]),
    ],
  },

  linux: {
    name: `Linux`, icon: `🐧`, kind: `Système`,
    questions: [
      Q(`Quelle commande liste le contenu d'un dossier ?`, [`ls`, `list`, `show`, `lf`]),
      Q(`Quelle commande affiche le dossier courant ?`, [`pwd`, `cd`, `whereami`, `path`]),
      Q(`Quelle commande change les permissions d'un fichier ?`, [`chmod`, `chown`, `chperm`, `perm`]),
      Q(`À quelles permissions correspond chmod 755 ?`, [`rwxr-xr-x`, `rwxrwxrwx`, `rw-r--r--`, `r-xr-xr-x`]),
      Q(`Comment s'appelle le compte superutilisateur ?`, [`root`, `admin`, `sudo`, `super`]),
      Q(`Quelle commande recherche un motif de texte dans des fichiers ?`, [`grep`, `find`, `locate`, `which`]),
      Q(`Quelle commande recherche des fichiers par nom dans une arborescence ?`, [`find`, `grep`, `cat`, `head`]),
      Q(`Quelle commande affiche les processus en temps réel ?`, [`top`, `ps --live`, `proc`, `tasks`]),
      Q(`Comment terminer le processus 1234 ?`, [`kill 1234`, `stop 1234`, `end 1234`, `rm 1234`]),
      Q(`Que fait le pipe | ?`, [`Il envoie la sortie d'une commande en entrée de la suivante`, `Il redirige la sortie vers un fichier`, `Il lance une commande en arrière-plan`, `Il commente la ligne`]),
      Q(`Quelle est la différence entre > et >> ?`, [`> écrase le fichier, >> ajoute à la fin`, `> ajoute à la fin, >> écrase le fichier`, `Aucune différence`, `>> crée un dossier`]),
      Q(`Quel dossier contient la plupart des fichiers de configuration système ?`, [`/etc`, `/bin`, `/home`, `/tmp`]),
      Q(`Par quel caractère commence le nom d'un fichier caché ?`, [`.`, `_`, `~`, `#`]),
      Q(`Que montre ls -la ?`, [`Tous les fichiers, cachés inclus, en format détaillé`, `Seulement les fichiers cachés`, `Les fichiers triés par taille uniquement`, `Les liens symboliques uniquement`]),
      Q(`Quel est le gestionnaire de paquets de Debian/Ubuntu ?`, [`apt`, `yum`, `pacman`, `brew`]),
      Q(`Que fait sudo ?`, [`Exécute une commande avec les droits d'un autre utilisateur (root par défaut)`, `Supprime un utilisateur`, `Change de dossier`, `Redémarre la machine`]),
      Q(`Quelle commande affiche l'espace libre sur les disques ?`, [`df -h`, `free -h`, `ls -s`, `top -d`]),
      Q(`Que désigne ~ dans un chemin ?`, [`Le dossier personnel de l'utilisateur`, `La racine du système`, `Le dossier /tmp`, `Le dossier précédent`]),
      Q(`Quel code de sortie indique qu'une commande a réussi ?`, [`0`, `1`, `-1`, `255`]),
      Q(`Quel est le port par défaut de SSH ?`, [`22`, `21`, `80`, `443`]),
      Q(`Quelle commande affiche les 10 dernières lignes d'un fichier ?`, [`tail`, `head`, `less`, `cut`]),
      Q(`Quelle commande liste le contenu d'un dossier ?`, [`ls`, `dir`, `list`, `show`]),
      Q(`Quelle commande change de répertoire ?`, [`cd`, `chdir`, `move`, `go`]),
      Q(`Quelle commande affiche le répertoire courant ?`, [`pwd`, `cwd`, `where`, `path`]),
      Q(`Quelle commande crée un dossier ?`, [`mkdir`, `touch`, `newdir`, `create`]),
      Q(`Que fait chmod 755 fichier ?`, [`Modifie les permissions du fichier`, `Change le propriétaire`, `Supprime le fichier`, `Compresse le fichier`]),
      Q(`Quel caractère redirige la sortie vers un fichier (écrasement) ?`, [`>`, `>>`, `|`, `<`]),
      Q(`Que fait le symbole | (pipe) ?`, [`Envoie la sortie d'une commande vers l'entrée d'une autre`, `Exécute deux commandes en parallèle`, `Commente la ligne`, `Redirige vers un fichier`]),
      Q(`Quelle commande recherche du texte dans des fichiers ?`, [`grep`, `find`, `search`, `locate text`]),
      Q(`Quelle commande affiche les processus en cours ?`, [`ps`, `jobs only`, `proc`, `tasklist`]),
    ],
  },

  docker: {
    name: `Docker`, icon: `🐳`, kind: `DevOps`,
    questions: [
      Q(`Quelle est la relation entre une image et un conteneur ?`, [`Un conteneur est une instance en exécution d'une image`, `Une image est un conteneur arrêté`, `Ce sont deux noms pour la même chose`, `Une image contient plusieurs machines virtuelles`]),
      Q(`Quel fichier décrit comment construire une image ?`, [`Dockerfile`, `docker.yml`, `image.json`, `build.txt`]),
      Q(`Quelle commande construit une image à partir du dossier courant ?`, [`docker build -t mon-app .`, `docker create mon-app`, `docker make mon-app`, `docker compile .`]),
      Q(`Quelle commande liste les conteneurs en cours d'exécution ?`, [`docker ps`, `docker images`, `docker list`, `docker show`]),
      Q(`Quelle commande liste les images locales ?`, [`docker images`, `docker ps`, `docker pull`, `docker layers`]),
      Q(`Que signifie -p 8080:80 dans docker run ?`, [`Le port 8080 de l'hôte redirige vers le port 80 du conteneur`, `Le port 80 de l'hôte redirige vers le 8080 du conteneur`, `Le conteneur utilise 8080 Mo de RAM`, `Le conteneur aura 80 processus max`]),
      Q(`Quelle option lance un conteneur en arrière-plan ?`, [`-d`, `-b`, `--background`, `-x`]),
      Q(`Quel outil définit et lance des applications multi-conteneurs via un fichier YAML ?`, [`Docker Compose`, `Docker Hub`, `Dockerfile`, `Docker Desktop`]),
      Q(`Quelle instruction définit l'image de base dans un Dockerfile ?`, [`FROM`, `BASE`, `IMAGE`, `START`]),
      Q(`Quelle est la différence entre RUN et CMD ?`, [`RUN s'exécute pendant le build, CMD au démarrage du conteneur`, `RUN s'exécute au démarrage, CMD pendant le build`, `Ce sont des synonymes`, `CMD est obsolète`]),
      Q(`Comment conserver des données au-delà de la vie d'un conteneur ?`, [`Avec un volume`, `Avec un tag`, `Avec un label`, `Avec EXPOSE`]),
      Q(`Comment ouvrir un shell dans un conteneur qui tourne ?`, [`docker exec -it <id> sh`, `docker run -it <id>`, `docker ssh <id>`, `docker open <id>`]),
      Q(`Quelle commande affiche les logs d'un conteneur ?`, [`docker logs <id>`, `docker output <id>`, `docker tail <id>`, `docker show-logs <id>`]),
      Q(`Quel est le registre public d'images par défaut ?`, [`Docker Hub`, `GitHub Pages`, `npm`, `PyPI`]),
      Q(`À quoi sert .dockerignore ?`, [`Exclure des fichiers du contexte envoyé au build`, `Ignorer certains conteneurs au démarrage`, `Masquer des logs`, `Désactiver le cache`]),
      Q(`Que crée chaque instruction RUN, COPY ou ADD ?`, [`Une nouvelle couche (layer) de l'image`, `Un nouveau conteneur`, `Un nouveau volume`, `Un nouveau réseau`]),
      Q(`Quel est l'intérêt principal d'un build multi-stage ?`, [`Réduire la taille de l'image finale`, `Lancer plusieurs conteneurs à la fois`, `Accélérer le réseau`, `Chiffrer l'image`]),
      Q(`Que fait docker compose down ?`, [`Arrête et supprime les conteneurs et réseaux du projet`, `Supprime toutes les images de la machine`, `Met les conteneurs en pause`, `Télécharge les dernières images`]),
      Q(`Que fait l'instruction EXPOSE 80 ?`, [`Elle documente le port écouté, sans le publier sur l'hôte`, `Elle publie automatiquement le port 80 sur l'hôte`, `Elle ouvre le pare-feu de l'hôte`, `Elle redirige le port 80 vers 8080`]),
      Q(`Sur quelles fonctionnalités du noyau Linux repose l'isolation des conteneurs ?`, [`Les namespaces et les cgroups`, `Un hyperviseur de type 1`, `Des machines virtuelles complètes`, `Le BIOS`]),
      Q(`Quelle commande télécharge une image sans la lancer ?`, [`docker pull nginx`, `docker get nginx`, `docker fetch nginx`, `docker load nginx`]),
      Q(`Quel fichier décrit la construction d'une image ?`, [`Dockerfile`, `docker.yml`, `image.conf`, `build.json`]),
      Q(`Quelle commande liste les conteneurs en cours d'exécution ?`, [`docker ps`, `docker list`, `docker ls`, `docker show`]),
      Q(`Quelle commande construit une image à partir d'un Dockerfile ?`, [`docker build`, `docker make`, `docker create`, `docker compile`]),
      Q(`Qu'est-ce qu'une image Docker ?`, [`Un modèle en lecture seule servant à créer des conteneurs`, `Un conteneur en cours d'exécution`, `Un fichier de logs`, `Une machine virtuelle complète`]),
      Q(`Quel fichier orchestre plusieurs conteneurs ?`, [`docker-compose.yml`, `Dockerfile`, `containers.json`, `stack.conf`]),
      Q(`Que fait l'option -d dans docker run -d ?`, [`Lance le conteneur en arrière-plan (detached)`, `Supprime le conteneur à l'arrêt`, `Active le mode debug`, `Monte un volume`]),
      Q(`À quoi sert un volume Docker ?`, [`Persister des données hors du cycle de vie du conteneur`, `Accélérer le réseau`, `Chiffrer l'image`, `Limiter la RAM`]),
      Q(`Quelle commande arrête un conteneur ?`, [`docker stop`, `docker kill only`, `docker end`, `docker halt`]),
    ],
  },

  kubernetes: {
    name: `Kubernetes`, icon: `☸️`, kind: `Cloud`,
    questions: [
      Q(`Quelle est la plus petite unité déployable dans Kubernetes ?`, [`Le Pod`, `Le conteneur`, `Le nœud`, `Le Service`]),
      Q(`Quel outil en ligne de commande pilote un cluster ?`, [`kubectl`, `dockerctl`, `k8sctl`, `kubesh`]),
      Q(`Pourquoi abrège-t-on Kubernetes en « k8s » ?`, [`Il y a 8 lettres entre le k et le s`, `C'est la version 8`, `Il faut 8 nœuds minimum`, `Il a été créé en 2008`]),
      Q(`Que gère un Deployment ?`, [`Des ReplicaSets et leurs Pods, avec mises à jour progressives`, `Des volumes persistants`, `Des namespaces`, `Les nœuds du cluster`]),
      Q(`Quel est le type de Service par défaut ?`, [`ClusterIP`, `NodePort`, `LoadBalancer`, `ExternalName`]),
      Q(`Quel type de Service expose une application sur un port de chaque nœud ?`, [`NodePort`, `ClusterIP`, `ExternalName`, `Headless`]),
      Q(`Quel objet stocke une configuration NON sensible ?`, [`ConfigMap`, `Secret`, `Volume`, `Annotation`]),
      Q(`Quel objet stocke des données sensibles (mots de passe, tokens) ?`, [`Secret`, `ConfigMap`, `Label`, `PodSpec`]),
      Q(`À quoi sert un Ingress ?`, [`Router le trafic HTTP/HTTPS externe vers des Services`, `Stocker des images`, `Planifier les Pods sur les nœuds`, `Sauvegarder etcd`]),
      Q(`À quoi sert un Namespace ?`, [`Isoler logiquement des ressources dans un même cluster`, `Nommer les conteneurs`, `Créer un nouveau cluster`, `Chiffrer les Pods`]),
      Q(`Qu'est-ce qu'etcd ?`, [`La base clé-valeur qui stocke l'état du cluster`, `Un plugin réseau`, `Un registre d'images`, `Un outil de monitoring`]),
      Q(`Quel est le rôle du kubelet ?`, [`Agent sur chaque nœud qui fait tourner les conteneurs des Pods`, `Il répartit le trafic entre Services`, `Il stocke les Secrets`, `Il compile les images`]),
      Q(`Quel composant décide sur quel nœud placer un Pod ?`, [`kube-scheduler`, `kubelet`, `etcd`, `kube-proxy`]),
      Q(`Comment passer le Deployment « app » à 5 réplicas ?`, [`kubectl scale deployment app --replicas=5`, `kubectl resize app 5`, `kubectl replicas app=5`, `kubectl grow app 5`]),
      Q(`Que fait un HorizontalPodAutoscaler (HPA) ?`, [`Il ajuste le nombre de Pods selon la charge (CPU, mémoire…)`, `Il ajoute des nœuds physiques`, `Il augmente la RAM d'un Pod`, `Il met à jour les images`]),
      Q(`Que se passe-t-il quand une liveness probe échoue ?`, [`Le conteneur est redémarré`, `Le Pod est retiré du Service sans redémarrer`, `Le nœud est supprimé`, `Rien, c'est informatif`]),
      Q(`À quoi sert une readiness probe ?`, [`Indiquer si le Pod est prêt à recevoir du trafic`, `Redémarrer le conteneur`, `Mesurer la latence réseau`, `Valider le YAML`]),
      Q(`Quelle commande applique un manifeste YAML ?`, [`kubectl apply -f app.yaml`, `kubectl run -f app.yaml`, `kubectl deploy app.yaml`, `kubectl up app.yaml`]),
      Q(`Quel objet convient à une base de données (identité stable, stockage persistant) ?`, [`StatefulSet`, `Deployment`, `DaemonSet`, `Job`]),
      Q(`Que garantit un DaemonSet ?`, [`Une copie du Pod sur chaque nœud (ou une sélection de nœuds)`, `Exactement un Pod dans tout le cluster`, `Un Pod qui s'exécute une seule fois`, `Un Pod relancé chaque nuit`]),
      Q(`Comment voir les logs d'un Pod ?`, [`kubectl logs <pod>`, `kubectl get logs <pod>`, `kubectl tail <pod>`, `kubectl output <pod>`]),
      Q(`Quelle est la plus petite unité déployable dans Kubernetes ?`, [`Le Pod`, `Le conteneur`, `Le Node`, `Le Service`]),
      Q(`Quel objet expose un ensemble de Pods derrière une IP stable ?`, [`Service`, `Deployment`, `ConfigMap`, `Namespace`]),
      Q(`Quel objet gère les mises à jour et le nombre de réplicas ?`, [`Deployment`, `Pod`, `Ingress`, `Secret`]),
      Q(`Quelle commande liste les Pods ?`, [`kubectl get pods`, `kubectl list pods`, `kubectl show pods`, `kubectl pods`]),
      Q(`Où stocke-t-on des données de configuration non sensibles ?`, [`ConfigMap`, `Secret`, `Volume`, `Pod`]),
      Q(`Quel composant planifie les Pods sur les nœuds ?`, [`Le scheduler`, `Le kubelet`, `Le proxy`, `L'etcd`]),
      Q(`Qu'est-ce qu'un Node ?`, [`Une machine (VM ou physique) du cluster`, `Un groupe de services`, `Un fichier YAML`, `Un conteneur unique`]),
    ],
  },

  aws: {
    name: `AWS`, icon: `🟧`, kind: `Cloud`,
    questions: [
      Q(`Quel service AWS fournit du stockage d'objets ?`, [`S3`, `EC2`, `RDS`, `Lambda`]),
      Q(`Quel service fournit des serveurs virtuels ?`, [`EC2`, `S3`, `IAM`, `CloudFront`]),
      Q(`Quel service exécute du code sans gérer de serveur (serverless) ?`, [`Lambda`, `EC2`, `EBS`, `Lightsail`]),
      Q(`Quel service gère utilisateurs, rôles et permissions sur les ressources AWS ?`, [`IAM`, `CloudTrail`, `KMS`, `Route 53`]),
      Q(`Quel est le service DNS d'AWS ?`, [`Route 53`, `CloudFront`, `VPC`, `API Gateway`]),
      Q(`Quel service est le CDN d'AWS ?`, [`CloudFront`, `Route 53`, `S3 Glacier`, `Direct Connect`]),
      Q(`Quel service propose des bases relationnelles managées (MySQL, PostgreSQL…) ?`, [`RDS`, `DynamoDB`, `ElastiCache`, `S3`]),
      Q(`Quelle base NoSQL clé-valeur serverless propose AWS ?`, [`DynamoDB`, `RDS`, `Aurora`, `Athena`]),
      Q(`Quel service collecte métriques, logs et alarmes ?`, [`CloudWatch`, `CloudFormation`, `Route 53`, `IAM`]),
      Q(`Quel service enregistre l'historique des appels d'API (audit) ?`, [`CloudTrail`, `CloudWatch`, `Inspector`, `Shield`]),
      Q(`Quel service fait de l'Infrastructure as Code native ?`, [`CloudFormation`, `CloudFront`, `CloudWatch`, `Cloud9`]),
      Q(`Comment s'appelle le réseau virtuel isolé dans AWS ?`, [`VPC`, `VPN`, `LAN Zone`, `Direct Connect`]),
      Q(`Qu'est-ce qu'une Availability Zone (AZ) ?`, [`Un ou plusieurs datacenters isolés au sein d'une Région`, `Une Région entière`, `Un point de présence du CDN`, `Un compte AWS`]),
      Q(`Quel stockage est conçu pour l'archivage à très bas coût ?`, [`S3 Glacier`, `EBS`, `EFS`, `S3 Standard`]),
      Q(`Quel stockage en mode bloc s'attache à une instance EC2 ?`, [`EBS`, `S3`, `Glacier`, `CloudFront`]),
      Q(`Dans le modèle de responsabilité partagée, AWS est responsable…`, [`De la sécurité DU cloud (matériel, datacenters, hyperviseur)`, `De la configuration de vos Security Groups`, `Du chiffrement de vos données applicatives`, `Des mots de passe de vos utilisateurs IAM`]),
      Q(`Qu'est-ce qu'un Security Group ?`, [`Un pare-feu virtuel avec état au niveau de l'instance`, `Un groupe d'utilisateurs IAM`, `Un antivirus managé`, `Un groupe de régions`]),
      Q(`Quel service est une file d'attente de messages ?`, [`SQS`, `SNS`, `SES`, `EMR`]),
      Q(`Quel service envoie des notifications en publication/abonnement (pub/sub) ?`, [`SNS`, `SQS`, `SES`, `EFS`]),
      Q(`Que fait EC2 Auto Scaling ?`, [`Il ajuste automatiquement le nombre d'instances selon la demande`, `Il augmente la taille du disque`, `Il change le type d'instance chaque nuit`, `Il réplique S3 dans une autre Région`]),
      Q(`Quel service répartit le trafic entre plusieurs instances ?`, [`Elastic Load Balancing`, `NAT Gateway`, `Internet Gateway`, `Route Table`]),
      Q(`Quel service est le stockage d'objets d'AWS ?`, [`S3`, `EBS`, `RDS`, `EFS`]),
      Q(`Quel service fournit des machines virtuelles ?`, [`EC2`, `S3`, `Lambda`, `Route 53`]),
      Q(`Quel service exécute du code sans gérer de serveur (serverless) ?`, [`Lambda`, `EC2`, `ECS`, `Fargate`]),
      Q(`Que signifie IAM ?`, [`Identity and Access Management`, `Internet Access Module`, `Instance Allocation Manager`, `Internal API Monitor`]),
      Q(`Quel service est une base de données NoSQL managée ?`, [`DynamoDB`, `RDS`, `Redshift`, `Aurora`]),
      Q(`Quel service gère le DNS ?`, [`Route 53`, `CloudFront`, `VPC`, `Direct Connect`]),
      Q(`Qu'est-ce qu'un VPC ?`, [`Un réseau virtuel privé isolé dans le cloud`, `Un service de calcul`, `Un type de base de données`, `Un pare-feu applicatif`]),
    ],
  },

  azure: {
    name: `Azure`, icon: `🔷`, kind: `Cloud`,
    questions: [
      Q(`Quel service Azure fournit des machines virtuelles ?`, [`Azure Virtual Machines`, `Azure Functions`, `Azure Blob Storage`, `Azure Cosmos DB`]),
      Q(`Quel service Azure exécute du code serverless déclenché par des événements ?`, [`Azure Functions`, `Azure Virtual Machines`, `Azure Arc`, `Azure Bastion`]),
      Q(`Quel service stocke des objets non structurés (images, vidéos, sauvegardes) ?`, [`Azure Blob Storage`, `Azure SQL Database`, `Azure Key Vault`, `Azure Monitor`]),
      Q(`Quel est le service d'identité de Microsoft (ex-Azure AD) ?`, [`Microsoft Entra ID`, `Azure Key Vault`, `Azure Policy`, `Azure Monitor`]),
      Q(`Quel service stocke secrets, clés et certificats ?`, [`Azure Key Vault`, `Microsoft Entra ID`, `Azure Files`, `Azure Advisor`]),
      Q(`Quel conteneur logique regroupe les ressources liées d'une même solution ?`, [`Un groupe de ressources (Resource Group)`, `Une région`, `Un tenant`, `Une zone de disponibilité`]),
      Q(`Quelle est la bonne hiérarchie ?`, [`Groupes d'administration > Abonnements > Groupes de ressources > Ressources`, `Abonnements > Groupes d'administration > Ressources > Groupes de ressources`, `Ressources > Groupes de ressources > Abonnements > Groupes d'administration`, `Groupes de ressources > Abonnements > Ressources > Groupes d'administration`]),
      Q(`Quelle base NoSQL multi-modèle distribuée mondialement propose Azure ?`, [`Azure Cosmos DB`, `Azure SQL Database`, `Azure Database for MySQL`, `Azure Synapse Analytics`]),
      Q(`Quel est le service Kubernetes managé d'Azure ?`, [`AKS`, `ACI`, `ACR`, `App Service`]),
      Q(`Quel service stocke des images de conteneurs privées ?`, [`Azure Container Registry (ACR)`, `Azure Kubernetes Service (AKS)`, `Azure Container Instances (ACI)`, `Azure Boards`]),
      Q(`Quel service lance un conteneur rapidement, sans orchestrateur ni VM à gérer ?`, [`Azure Container Instances (ACI)`, `Azure Kubernetes Service (AKS)`, `Azure Container Registry (ACR)`, `Azure Virtual Desktop`]),
      Q(`Quel service PaaS héberge des applications web et des API ?`, [`Azure App Service`, `Azure Virtual Machines`, `Azure Blob Storage`, `Azure Firewall`]),
      Q(`Quel service collecte métriques et logs pour surveiller les ressources ?`, [`Azure Monitor`, `Azure Advisor`, `Azure Policy`, `Azure Blueprints`]),
      Q(`Quel service donne des recommandations personnalisées (coût, sécurité, performance) ?`, [`Azure Advisor`, `Azure Monitor`, `Azure Policy`, `Azure Bastion`]),
      Q(`Quel service impose des règles de conformité (ex : régions autorisées) ?`, [`Azure Policy`, `Azure Advisor`, `Azure Monitor`, `Azure DNS`]),
      Q(`Que signifie RBAC ?`, [`Contrôle d'accès basé sur les rôles`, `Sauvegarde automatique des ressources`, `Réseau privé virtuel`, `Chiffrement au repos`]),
      Q(`Quel langage déclaratif natif simplifie l'écriture des templates ARM ?`, [`Bicep`, `HCL`, `Ansible`, `PowerShell DSC`]),
      Q(`Que sont les Availability Zones dans une région Azure ?`, [`Des datacenters physiquement séparés au sein d'une région`, `Des régions jumelées sur d'autres continents`, `Des abonnements séparés`, `Des groupes de ressources`]),
      Q(`Quel service fournit des pipelines CI/CD ?`, [`Azure Pipelines`, `Azure Boards`, `Azure Monitor`, `Azure Bastion`]),
      Q(`Quelle est la commande de l'Azure CLI ?`, [`az`, `azcli`, `azure`, `msaz`]),
      Q(`Quel service donne un accès RDP/SSH sécurisé via le navigateur, sans IP publique sur la VM ?`, [`Azure Bastion`, `Azure Firewall`, `VPN Gateway`, `Azure Front Door`]),
      Q(`Quel service fournit des machines virtuelles sur Azure ?`, [`Azure Virtual Machines`, `Azure Functions`, `Azure Blob`, `Azure SQL`]),
      Q(`Quel est le service de stockage d'objets d'Azure ?`, [`Blob Storage`, `Table Storage uniquement`, `Disk Storage`, `File Share`]),
      Q(`Quel service exécute du code serverless sur Azure ?`, [`Azure Functions`, `Azure VM`, `Azure Batch`, `Azure Kubernetes`]),
      Q(`Quel service gère les identités et l'authentification ?`, [`Microsoft Entra ID (Azure AD)`, `Azure Monitor`, `Azure Policy`, `Key Vault`]),
      Q(`Où stocker secrets, clés et certificats de façon sécurisée ?`, [`Azure Key Vault`, `Blob Storage`, `Azure Table`, `App Service`]),
      Q(`Quel service héberge des applications web managées ?`, [`Azure App Service`, `Azure Bastion`, `Azure DNS`, `Azure CDN`]),
      Q(`Quel regroupement logique contient des ressources Azure liées ?`, [`Resource Group`, `Subscription unique`, `Tenant`, `Region`]),
    ],
  },

  ai: {
    name: `Intelligence Artificielle`, icon: `🧠`, kind: `IA`,
    questions: [
      Q(`Que signifie « Machine Learning » ?`, [`L'apprentissage automatique à partir de données`, `La programmation manuelle de règles`, `Le câblage physique d'un ordinateur`, `La compression de fichiers`]),
      Q(`Dans l'apprentissage supervisé, les données sont…`, [`Étiquetées (on connaît la bonne réponse attendue)`, `Sans aucune étiquette`, `Toujours des images`, `Générées au hasard`]),
      Q(`Qu'est-ce que le surapprentissage (overfitting) ?`, [`Le modèle mémorise les données d'entraînement et généralise mal`, `Le modèle est trop simple`, `Le modèle s'entraîne trop vite`, `Le modèle manque de mémoire`]),
      Q(`Que signifie l'acronyme LLM ?`, [`Large Language Model (grand modèle de langage)`, `Low Level Machine`, `Linear Learning Method`, `Logical Language Mapper`]),
      Q(`Que signifie GPT ?`, [`Generative Pre-trained Transformer`, `General Processing Tool`, `Graphical Python Toolkit`, `Global Prediction Tensor`]),
      Q(`En traitement du langage, qu'est-ce qu'un « token » ?`, [`Une unité de texte (un mot ou un morceau de mot)`, `Un mot de passe`, `Une image`, `Un neurone`]),
      Q(`Qu'est-ce qu'un « prompt » pour un LLM ?`, [`L'instruction en langage naturel qu'on lui donne`, `Le nom du modèle`, `Un type de carte graphique`, `Une base de données`]),
      Q(`Qu'appelle-t-on « hallucination » d'un LLM ?`, [`Une réponse inventée présentée comme vraie`, `Un plantage du serveur`, `Un temps de réponse trop long`, `Une image générée`]),
      Q(`À quoi servent surtout les réseaux de neurones convolutifs (CNN) ?`, [`Au traitement des images`, `À trier des fichiers`, `À chiffrer des données`, `À compresser du son uniquement`]),
      Q(`Qu'est-ce que le « fine-tuning » ?`, [`Ré-entraîner un modèle pré-entraîné sur des données spécifiques`, `Supprimer un modèle`, `Accélérer le disque dur`, `Traduire du code`]),
      Q(`Dans l'apprentissage NON supervisé, on cherche surtout à…`, [`Trouver des structures ou des groupes sans étiquettes`, `Prédire une étiquette connue`, `Copier les données`, `Chiffrer les données`]),
      Q(`Que mesure l'« accuracy » (exactitude) d'un modèle ?`, [`La proportion de prédictions correctes`, `La vitesse du modèle`, `La taille du modèle`, `La mémoire consommée`]),
      Q(`Qu'est-ce qu'un « embedding » ?`, [`Une représentation vectorielle (numérique) d'une donnée`, `Un fichier image`, `Un pare-feu`, `Un langage de programmation`]),
      Q(`Que signifie RAG ?`, [`Retrieval-Augmented Generation (génération augmentée par recherche)`, `Random Access Gateway`, `Rapid AI Gradient`, `Recursive Analysis Graph`]),
      Q(`À quoi sert la descente de gradient (gradient descent) ?`, [`À ajuster les poids du modèle pour réduire l'erreur`, `À nettoyer les données`, `À afficher les résultats`, `À compresser le modèle`]),
      Q(`Que règle la « température » d'un LLM ?`, [`Le degré d'aléa et de créativité des réponses`, `La vitesse du GPU`, `La taille du vocabulaire`, `Le nombre maximum de tokens`]),
      Q(`Qu'est-ce qu'un « epoch » pendant l'entraînement ?`, [`Un passage complet sur tout le jeu de données`, `Une seule donnée`, `Un type de neurone`, `Un bug`]),
      Q(`Prédire un PRIX (un nombre continu) relève de la…`, [`Régression`, `Classification`, `Segmentation`, `Compression`]),
      Q(`Pourquoi sépare-t-on les données d'entraînement et de test ?`, [`Pour vérifier que le modèle généralise à des données nouvelles`, `Pour gagner de la place`, `Pour chiffrer les données`, `Par obligation légale`]),
      Q(`À quoi sert une fonction d'activation comme ReLU ?`, [`À introduire de la non-linéarité dans un neurone`, `À sauvegarder le modèle`, `À télécharger les données`, `À trier les colonnes`]),
      Q(`Qu'est-ce que l'apprentissage par renforcement ?`, [`Un agent apprend par essais, récompenses et pénalités`, `On étiquette toutes les données à la main`, `On copie un modèle existant`, `On supprime les mauvaises données`]),
      Q(`Qu'appelle-t-on « biais » d'un modèle d'IA ?`, [`Une tendance systématique à se tromper, souvent héritée des données`, `Une panne matérielle`, `Un virus`, `Un type de GPU`]),
      Q(`Que permettent des bibliothèques comme TensorFlow ou PyTorch ?`, [`Construire et entraîner des réseaux de neurones`, `Gérer une base SQL`, `Éditer des images`, `Envoyer des e-mails`]),
      Q(`Que signifie l'apprentissage supervisé ?`, [`On entraîne le modèle avec des données étiquetées`, `Le modèle apprend sans aucune donnée`, `On supervise manuellement chaque prédiction`, `Le modèle se corrige tout seul sans objectif`]),
      Q(`Qu'est-ce que le surapprentissage (overfitting) ?`, [`Le modèle mémorise les données d'entraînement et généralise mal`, `Le modèle est trop simple`, `Le jeu de données est trop grand`, `Le modèle apprend trop vite`]),
      Q(`Qu'est-ce qu'un LLM ?`, [`Un grand modèle de langage`, `Un langage de programmation`, `Une base de données vectorielle`, `Un protocole réseau`]),
      Q(`À quoi sert un jeu de données de test ?`, [`Évaluer le modèle sur des données jamais vues`, `Entraîner le modèle`, `Nettoyer les données`, `Stocker les poids`]),
      Q(`Qu'appelle-t-on un token dans un LLM ?`, [`Une unité de texte (mot ou fragment)`, `Un mot de passe`, `Un neurone`, `Une couche du réseau`]),
      Q(`Qu'est-ce que le machine learning ?`, [`Des algorithmes qui apprennent des motifs à partir de données`, `Des règles écrites à la main`, `Un type de base de données`, `Un langage de script`]),
      Q(`Que fait une fonction d'activation dans un neurone ?`, [`Introduire de la non-linéarité`, `Stocker les données`, `Trier les entrées`, `Compresser le modèle`]),
    ],
  },

  cybersecurite: {
    name: `Cybersécurité`, icon: `🛡️`, kind: `Sécurité`,
    questions: [
      Q(`Qu'est-ce que le « phishing » (hameçonnage) ?`, [`Piéger une victime pour qu'elle révèle ses informations`, `Chiffrer un disque dur`, `Scanner un réseau`, `Sauvegarder des données`]),
      Q(`À quoi sert un pare-feu (firewall) ?`, [`À filtrer le trafic réseau entrant et sortant`, `À accélérer Internet`, `À stocker des mots de passe`, `À compresser des fichiers`]),
      Q(`Que fait HTTPS de plus que HTTP ?`, [`Il chiffre la communication (via TLS)`, `Il va plus vite`, `Il bloque les publicités`, `Il compresse les images`]),
      Q(`Qu'est-ce qu'un ransomware (rançongiciel) ?`, [`Un logiciel qui chiffre vos fichiers et exige une rançon`, `Un antivirus gratuit`, `Un gestionnaire de mots de passe`, `Un pare-feu matériel`]),
      Q(`Que renforce l'authentification à deux facteurs (2FA) ?`, [`La connexion, en demandant une 2e preuve d'identité`, `La vitesse du site`, `La longueur des mots de passe`, `Le chiffrement du disque`]),
      Q(`En quoi consiste une attaque DDoS ?`, [`Saturer un service de requêtes pour le rendre indisponible`, `Voler une base de données`, `Cracker un mot de passe`, `Intercepter un e-mail`]),
      Q(`Contre quoi protègent principalement les requêtes SQL préparées ?`, [`L'injection SQL`, `Les attaques DDoS`, `Le phishing`, `Le vol d'ordinateur portable`]),
      Q(`Que signifie XSS ?`, [`Cross-Site Scripting (injection de script dans une page)`, `Extended Secure Shell`, `X.509 Signature System`, `Cross System Storage`]),
      Q(`À quoi sert un VPN ?`, [`À créer un tunnel chiffré pour votre trafic réseau`, `À supprimer les virus`, `À accélérer le processeur`, `À sauvegarder le cloud`]),
      Q(`Quelle est la différence entre hachage et chiffrement ?`, [`Le hachage est à sens unique (non réversible)`, `Le hachage est réversible, pas le chiffrement`, `Ce sont des synonymes`, `Le chiffrement est toujours plus lent à casser`]),
      Q(`Qu'est-ce qu'un « malware » ?`, [`Un logiciel malveillant (virus, ver, cheval de Troie…)`, `Un pare-feu`, `Un protocole réseau`, `Un mot de passe faible`]),
      Q(`Que dit le principe du moindre privilège ?`, [`Donner à chacun uniquement les droits dont il a besoin`, `Tout interdire aux administrateurs`, `Donner les droits admin à tout le monde`, `Changer de mot de passe chaque jour`]),
      Q(`Qu'est-ce qu'un CVE ?`, [`Un identifiant public d'une vulnérabilité connue`, `Un antivirus`, `Un type de pare-feu`, `Un algorithme de chiffrement`]),
      Q(`En quoi consiste une attaque par force brute ?`, [`Essayer de nombreuses combinaisons jusqu'à trouver le mot de passe`, `Envoyer un faux e-mail`, `Chiffrer un disque`, `Surcharger un serveur`]),
      Q(`Qu'est-ce qu'une faille « zero-day » ?`, [`Une vulnérabilité inconnue de l'éditeur, sans correctif disponible`, `Un virus datant de l'an 2000`, `Un mot de passe par défaut`, `Un pare-feu désactivé`]),
      Q(`Dans le chiffrement asymétrique, on utilise…`, [`Une clé publique et une clé privée`, `Une seule clé partagée`, `Aucune clé`, `Uniquement un mot de passe`]),
      Q(`Qu'est-ce que l'ingénierie sociale (social engineering) ?`, [`Manipuler des personnes pour obtenir des infos ou des accès`, `Configurer un réseau social`, `Programmer une IA`, `Chiffrer un e-mail`]),
      Q(`Que représente le triangle « CIA » en sécurité ?`, [`Confidentialité, Intégrité, Disponibilité`, `Contrôle, Identité, Accès`, `Cryptage, Internet, Antivirus`, `Certificat, IP, Authentification`]),
      Q(`Qu'est-ce qu'un test d'intrusion (pentest) ?`, [`Une attaque simulée et autorisée pour trouver les failles`, `Une sauvegarde chiffrée`, `Un simple scan antivirus`, `Un pare-feu applicatif`]),
      Q(`Qu'est-ce qu'une attaque « man-in-the-middle » ?`, [`Un attaquant intercepte la communication entre deux parties`, `Un virus sur une clé USB`, `Un mot de passe volé par force brute`, `Un déni de service`]),
      Q(`Pourquoi ajouter un « sel » (salt) à un mot de passe haché ?`, [`Pour contrer les attaques par tables précalculées (rainbow tables)`, `Pour le rendre plus court`, `Pour l'afficher en clair`, `Pour accélérer la connexion`]),
      Q(`Que fait un outil comme nmap ?`, [`Scanner les ports et services ouverts d'une machine`, `Chiffrer un disque`, `Envoyer des e-mails`, `Sauvegarder une base de données`]),
      Q(`Que garantit un certificat TLS/SSL valide pour un site ?`, [`L'identité du site et une connexion chiffrée`, `Que le site est gratuit`, `Que le site est rapide`, `Qu'il n'a aucun bug`]),
      Q(`Que signifie le phishing (hameçonnage) ?`, [`Tromper l'utilisateur pour voler ses identifiants`, `Saturer un serveur de requêtes`, `Chiffrer des fichiers contre rançon`, `Intercepter le trafic réseau`]),
      Q(`Quel principe limite les droits au strict nécessaire ?`, [`Le moindre privilège`, `La redondance`, `Le chiffrement total`, `La haute disponibilité`]),
      Q(`Qu'est-ce qu'un ransomware ?`, [`Un logiciel qui chiffre les données et exige une rançon`, `Un pare-feu`, `Un antivirus`, `Un gestionnaire de mots de passe`]),
      Q(`Que renforce l'authentification à deux facteurs (2FA) ?`, [`La sécurité de connexion en ajoutant une 2e preuve`, `La vitesse du site`, `Le chiffrement du disque`, `La sauvegarde des données`]),
      Q(`Que représentent les trois piliers de la sécurité (CIA) ?`, [`Confidentialité, Intégrité, Disponibilité`, `Contrôle, Identité, Accès`, `Chiffrement, Internet, Authentification`, `Cache, IP, Antivirus`]),
      Q(`Qu'est-ce qu'une attaque DDoS ?`, [`Saturer un service avec un trafic massif distribué`, `Voler une base de données`, `Deviner un mot de passe`, `Injecter du SQL`]),
      Q(`Pourquoi ne jamais stocker un mot de passe en clair ?`, [`En cas de fuite, ils seraient directement exploitables`, `Ça prend trop de place`, `C'est plus lent`, `Les hash sont illisibles pour le serveur`]),
    ],
  },

  cryptographie: {
    name: `Cryptographie`, icon: `🔐`, kind: `Sécurité`,
    questions: [
      Q(`Quel est le but principal du chiffrement ?`, [`Garantir la confidentialité des données`, `Accélérer le réseau`, `Compresser les fichiers`, `Supprimer les virus`]),
      Q(`Le chiffrement symétrique utilise…`, [`La même clé pour chiffrer et déchiffrer`, `Deux clés différentes`, `Aucune clé`, `Un simple mot de passe affiché`]),
      Q(`AES est un algorithme…`, [`Symétrique, par blocs`, `Asymétrique`, `De hachage`, `De compression`]),
      Q(`RSA est un algorithme…`, [`Asymétrique (à clé publique)`, `Symétrique`, `De hachage`, `De sauvegarde`]),
      Q(`À quoi sert une fonction de hachage ?`, [`Produire une empreinte de taille fixe, à sens unique`, `Chiffrer de façon réversible`, `Compresser un fichier`, `Signer automatiquement un e-mail`]),
      Q(`Combien de bits produit SHA-256 ?`, [`256`, `128`, `512`, `64`]),
      Q(`Pour signer numériquement un message, on utilise…`, [`Sa propre clé privée`, `La clé publique du destinataire`, `Un mot de passe partagé`, `La clé privée du destinataire`]),
      Q(`Pour vérifier une signature numérique, on utilise…`, [`La clé publique de l'expéditeur`, `Sa propre clé privée`, `Le certificat du destinataire`, `Un sel aléatoire`]),
      Q(`À quoi sert l'échange Diffie-Hellman ?`, [`À établir une clé secrète sur un canal non sûr`, `À hacher un mot de passe`, `À signer un fichier`, `À compresser une clé`]),
      Q(`Pourquoi ajouter un « sel » à un mot de passe avant hachage ?`, [`Pour rendre chaque empreinte unique et contrer les rainbow tables`, `Pour le raccourcir`, `Pour l'afficher en clair`, `Pour le chiffrer deux fois`]),
      Q(`Que garantit principalement un HMAC ?`, [`L'intégrité et l'authenticité d'un message`, `La confidentialité seule`, `La compression`, `La vitesse`]),
      Q(`Quel est l'avantage du chiffrement symétrique sur l'asymétrique ?`, [`Il est beaucoup plus rapide`, `Il n'a pas besoin de clé`, `Il est incassable`, `Il ne nécessite aucun secret`]),
      Q(`Dans TLS, à quoi sert surtout la cryptographie asymétrique ?`, [`À échanger/établir en sécurité la clé de session`, `À chiffrer toutes les données du site`, `À compresser les pages`, `À stocker les cookies`]),
      Q(`Qu'est-ce qu'une « collision » de hachage ?`, [`Deux entrées différentes donnent la même empreinte`, `Deux clés identiques`, `Un certificat expiré`, `Un mot de passe trop court`]),
      Q(`À quoi lie un certificat numérique une clé publique ?`, [`À une identité (personne, site…)`, `À un mot de passe`, `À une adresse IP fixe`, `À un numéro de série de disque`]),
      Q(`Qui émet et signe les certificats de confiance ?`, [`Une autorité de certification (CA)`, `Le navigateur du visiteur`, `Le fournisseur d'accès`, `Le serveur DNS`]),
      Q(`Qu'est-ce qu'un « nonce » en cryptographie ?`, [`Une valeur utilisée une seule fois`, `Une clé privée`, `Un type de virus`, `Un mot de passe par défaut`]),
      Q(`Que garantit le chiffrement de bout en bout (E2EE) ?`, [`Seuls l'émetteur et le destinataire peuvent lire le message`, `Le serveur peut tout lire`, `Les messages ne sont jamais chiffrés`, `Une vitesse maximale`]),
      Q(`Pourquoi ne jamais stocker un mot de passe en clair ?`, [`En cas de fuite, tous seraient immédiatement exposés`, `Ça prend trop de place`, `C'est plus lent`, `Ça empêche la connexion`]),
      Q(`Quelle taille de clé AES est considérée comme sûre aujourd'hui ?`, [`128 ou 256 bits`, `8 bits`, `16 bits`, `40 bits`]),
      Q(`Quelle est la différence clé entre chiffrement symétrique et asymétrique ?`, [`Symétrique : une seule clé ; asymétrique : paire publique/privée`, `Le symétrique utilise deux clés`, `L'asymétrique n'utilise aucune clé`, `Aucune différence`]),
      Q(`AES est un algorithme de chiffrement…`, [`Symétrique`, `Asymétrique`, `De hachage`, `De compression`]),
      Q(`RSA est un algorithme…`, [`Asymétrique (clé publique)`, `Symétrique`, `De hachage`, `De signature uniquement`]),
      Q(`Une fonction de hachage est-elle réversible ?`, [`Non, elle est à sens unique`, `Oui, avec la clé`, `Oui, toujours`, `Seulement pour SHA-256`]),
      Q(`Lequel est une fonction de hachage ?`, [`SHA-256`, `AES`, `RSA`, `Diffie-Hellman`]),
      Q(`À quoi sert le « salage » (salt) d'un mot de passe ?`, [`Ajouter une valeur aléatoire pour éviter les attaques par table`, `Chiffrer le mot de passe`, `Le compresser`, `Le rendre plus court`]),
      Q(`À quoi sert une signature numérique ?`, [`Prouver l'authenticité et l'intégrité d'un message`, `Chiffrer un disque`, `Compresser un fichier`, `Accélérer le TLS`]),
    ],
  },

  securiteweb: {
    name: `Sécurité Web (OWASP)`, icon: `🕸️`, kind: `Sécurité`,
    questions: [
      Q(`En quoi consiste une injection SQL ?`, [`Insérer du SQL malveillant via une entrée non filtrée`, `Surcharger le serveur`, `Voler un ordinateur`, `Chiffrer la base`]),
      Q(`Quelle est la meilleure protection contre l'injection SQL ?`, [`Les requêtes paramétrées (préparées)`, `Cacher le formulaire`, `Un mot de passe plus long`, `Désactiver le HTTPS`]),
      Q(`Qu'est-ce qu'une attaque XSS ?`, [`Injecter du JavaScript exécuté dans le navigateur de la victime`, `Scanner les ports`, `Chiffrer les cookies`, `Saturer le réseau`]),
      Q(`Comment se défend-on principalement contre le XSS ?`, [`Échapper/encoder les sorties et utiliser une CSP`, `Augmenter la RAM`, `Désactiver JavaScript côté serveur`, `Changer de port`]),
      Q(`Qu'est-ce qu'une attaque CSRF ?`, [`Forcer la victime à envoyer une requête à son insu`, `Lire la base de données`, `Casser un mot de passe`, `Intercepter le Wi-Fi`]),
      Q(`Quelle défense classique contre le CSRF ?`, [`Un jeton anti-CSRF unique par formulaire`, `Un mot de passe plus long`, `Désactiver les cookies`, `Un pare-feu matériel`]),
      Q(`Quel attribut empêche un cookie d'être lu par JavaScript ?`, [`HttpOnly`, `Secure`, `SameSite`, `Path`]),
      Q(`Quel attribut limite l'envoi d'un cookie aux requêtes du même site ?`, [`SameSite`, `HttpOnly`, `Secure`, `Domain`]),
      Q(`Quel attribut impose qu'un cookie ne circule qu'en HTTPS ?`, [`Secure`, `HttpOnly`, `SameSite`, `Expires`]),
      Q(`Qu'est-ce qu'une attaque SSRF ?`, [`Forcer le serveur à requêter une ressource interne`, `Injecter du HTML`, `Voler un cookie`, `Deviner un mot de passe`]),
      Q(`Qu'est-ce qu'une faille IDOR ?`, [`Accéder aux données d'un autre en changeant un identifiant`, `Injecter du SQL`, `Saturer le serveur`, `Falsifier un certificat`]),
      Q(`À quoi sert une Content-Security-Policy (CSP) ?`, [`Restreindre les sources de scripts/ressources autorisées`, `Compresser les images`, `Accélérer le DNS`, `Chiffrer la base`]),
      Q(`Que force l'en-tête HSTS ?`, [`L'utilisation de HTTPS pour le domaine`, `La mise en cache`, `L'ouverture d'un port`, `La compression gzip`]),
      Q(`Que fait la Same-Origin Policy du navigateur ?`, [`Empêche un site de lire les données d'une autre origine`, `Bloque les pubs`, `Chiffre les cookies`, `Accélère le rendu`]),
      Q(`À quoi sert le mécanisme CORS ?`, [`Autoriser de façon contrôlée des requêtes cross-origin`, `Bloquer tout JavaScript`, `Chiffrer les formulaires`, `Scanner les ports`]),
      Q(`Par quel en-tête contre-t-on le clickjacking ?`, [`X-Frame-Options (ou frame-ancestors)`, `Content-Type`, `Accept-Language`, `Cache-Control`]),
      Q(`Que permet une attaque de type « path traversal » (../) ?`, [`Accéder à des fichiers hors du dossier prévu`, `Injecter du SQL`, `Voler un cookie`, `Saturer le CPU`]),
      Q(`Qu'est-ce que l'OWASP Top 10 ?`, [`Une liste des risques de sécurité web les plus critiques`, `Un pare-feu`, `Un langage de script`, `Un navigateur sécurisé`]),
      Q(`Qu'est-ce qu'un JWT ?`, [`Un jeton signé contenant des informations de session`, `Un pare-feu applicatif`, `Un algorithme de hachage`, `Un type de cookie tiers`]),
      Q(`Quelle est la règle d'or vis-à-vis des entrées utilisateur ?`, [`Ne jamais leur faire confiance : toujours valider et nettoyer`, `Les stocker en clair`, `Les exécuter directement`, `Les afficher sans échappement`]),
      Q(`Que vise une attaque XSS ?`, [`Injecter du JavaScript exécuté dans le navigateur de la victime`, `Injecter du SQL dans la base`, `Saturer le serveur`, `Voler le certificat TLS`]),
      Q(`Comment se protège-t-on principalement des injections SQL ?`, [`Avec des requêtes préparées (paramétrées)`, `En désactivant JavaScript`, `En cachant l'URL`, `En utilisant HTTPS seulement`]),
      Q(`Que signifie CSRF ?`, [`Cross-Site Request Forgery`, `Cross-Site Resource Fetch`, `Client Secure Request Form`, `Common Server Response Filter`]),
      Q(`Contre quoi protège l'échappement des sorties HTML ?`, [`Les attaques XSS`, `Les injections SQL`, `Les attaques DDoS`, `Le brute force`]),
      Q(`Qu'est-ce qu'une faille d'injection au sens OWASP ?`, [`Des données non fiables interprétées comme commande/requête`, `Un mot de passe faible`, `Un certificat expiré`, `Un port ouvert`]),
      Q(`Pourquoi ne pas exposer des messages d'erreur détaillés en production ?`, [`Ils donnent des infos exploitables à un attaquant`, `Ils ralentissent le site`, `Ils cassent le CSS`, `Ils augmentent la bande passante`]),
      Q(`Que recommande OWASP pour stocker les mots de passe ?`, [`Un hachage lent et salé (bcrypt, Argon2)`, `MD5`, `Base64`, `En clair chiffré AES`]),
    ],
  },

  pentest: {
    name: `Hacking & Pentest`, icon: `🥷`, kind: `Sécurité`,
    questions: [
      Q(`Qu'est-ce qu'un test d'intrusion (pentest) ?`, [`Une attaque autorisée pour trouver les failles d'un système`, `Un virus informatique`, `Une sauvegarde chiffrée`, `Un pare-feu`]),
      Q(`Quelle est la première phase d'un pentest ?`, [`La reconnaissance (collecte d'informations)`, `La rédaction du rapport`, `L'effacement des traces`, `L'exploitation`]),
      Q(`Que signifie OSINT ?`, [`Le renseignement à partir de sources ouvertes/publiques`, `Un scanner de ports`, `Un type de chiffrement`, `Un pare-feu applicatif`]),
      Q(`À quoi sert l'outil nmap ?`, [`Scanner les ports et services d'une machine`, `Casser des mots de passe`, `Éditer des images`, `Chiffrer un disque`]),
      Q(`À quoi sert Wireshark ?`, [`Analyser (sniffer) le trafic réseau`, `Compiler du code`, `Scanner des ports uniquement`, `Gérer une base de données`]),
      Q(`Qu'est-ce que Metasploit ?`, [`Un framework d'exploitation de vulnérabilités`, `Un navigateur`, `Un gestionnaire de mots de passe`, `Un antivirus`]),
      Q(`À quoi sert surtout Burp Suite ?`, [`Tester la sécurité des applications web (proxy d'interception)`, `Défragmenter le disque`, `Compiler du C`, `Gérer des conteneurs`]),
      Q(`Qu'est-ce que Kali Linux ?`, [`Une distribution Linux orientée tests d'intrusion`, `Un antivirus`, `Un pare-feu matériel`, `Un langage de script`]),
      Q(`À quoi servent hashcat et John the Ripper ?`, [`À casser des mots de passe (hachés)`, `À scanner des ports`, `À chiffrer un disque`, `À analyser le trafic`]),
      Q(`À quoi sert l'outil hydra ?`, [`Force brute sur des services d'authentification`, `Analyse de paquets`, `Compression de fichiers`, `Signature de code`]),
      Q(`Qu'est-ce qu'un reverse shell ?`, [`La cible se connecte à l'attaquant pour lui ouvrir un shell`, `Un shell qui s'auto-répare`, `Un antivirus`, `Un pare-feu`]),
      Q(`Qu'est-ce que l'élévation de privilèges ?`, [`Passer d'un accès limité à un accès administrateur/root`, `Changer de mot de passe`, `Redémarrer le serveur`, `Compresser des logs`]),
      Q(`Qu'est-ce que le mouvement latéral ?`, [`Se propager vers d'autres machines du réseau compromis`, `Monter en privilèges`, `Chiffrer un disque`, `Scanner un port`]),
      Q(`Qu'appelle-t-on « persistance » en sécurité offensive ?`, [`Maintenir un accès même après redémarrage`, `Sauvegarder les données`, `Augmenter la RAM`, `Changer d'adresse IP`]),
      Q(`Que faut-il impérativement avant tout pentest ?`, [`Une autorisation écrite et un périmètre défini`, `Un bon antivirus`, `Une connexion rapide`, `Un compte administrateur public`]),
      Q(`Qu'est-ce que la divulgation responsable (responsible disclosure) ?`, [`Signaler une faille à l'éditeur avant toute publication`, `Vendre la faille au plus offrant`, `Publier l'exploit immédiatement`, `Ignorer la faille`]),
      Q(`Qu'est-ce qu'un programme de bug bounty ?`, [`Un programme qui récompense la découverte de failles`, `Un virus propagé par e-mail`, `Un pare-feu payant`, `Un scanner automatique`]),
      Q(`Que désignent la « red team » et la « blue team » ?`, [`Les attaquants simulés et les défenseurs`, `Deux antivirus concurrents`, `Deux types de pare-feu`, `Deux versions de Linux`]),
      Q(`Qu'est-ce qu'un exploit ?`, [`Un code qui tire parti d'une vulnérabilité`, `Un mot de passe fort`, `Un certificat TLS`, `Un pare-feu`]),
      Q(`Qu'est-ce que l'énumération lors d'un pentest ?`, [`Lister utilisateurs, partages et services d'une cible`, `Chiffrer les données`, `Effacer les logs`, `Rédiger le rapport final`]),
      Q(`Quel outil scanne les ports ouverts d'une machine ?`, [`Nmap`, `Wireshark`, `John the Ripper`, `Burp Suite`]),
      Q(`Quelle est la première phase d'un pentest ?`, [`La reconnaissance`, `L'exploitation`, `Le nettoyage`, `L'escalade de privilèges`]),
      Q(`Que signifie « chapeau blanc » (white hat) ?`, [`Un hacker éthique qui agit avec autorisation`, `Un cybercriminel`, `Un virus`, `Un pare-feu`]),
      Q(`Quel outil analyse le trafic réseau (sniffing) ?`, [`Wireshark`, `Nmap`, `Metasploit`, `Hydra`]),
      Q(`Qu'est-ce que l'escalade de privilèges ?`, [`Obtenir des droits plus élevés que ceux accordés`, `Scanner un réseau`, `Chiffrer un disque`, `Envoyer un phishing`]),
      Q(`Quel framework est célèbre pour développer et lancer des exploits ?`, [`Metasploit`, `Wireshark`, `Nikto`, `Aircrack`]),
      Q(`Avant tout test d'intrusion légal, que faut-il obligatoirement obtenir ?`, [`Une autorisation écrite du propriétaire`, `Un VPN`, `Un antivirus`, `Une adresse IP fixe`]),
    ],
  },
};

module.exports = { THEMES };
